networks:
  traffic-light:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services: 
  red-app:
    # image: trafficlight/red:v1.0
    build:
      context: ./red
    networks:
      - traffic-light

  yellow-app:
    # image: trafficlight/yellow:v1.0
    build:
      context: ./yellow
    networks:
      - traffic-light
  
  green-app:
    # image: trafficlight/green:v1.0
    build:
      context: ./green
    networks:
      - traffic-light

  nginx-proxy:
    image: nginx:1.21
    networks:
      - traffic-light
    volumes: 
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"

  nginx-load-balancer:   
    image: nginx:1.21
    networks:
      - traffic-light
    volumes: 
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
    ports:
      - "8000:8000"